
#include "words.h"
/* NOTE: EVERY MESSAGE MUST END WITH A #!!! */
char word_list[] = "\
naked#\
I am not a crook#\
Bertrand#\
stop me before I kill again#\
sausage#\
all night#\
if you want#\
please#\
YES#\
NO#\
again#\
touch me#\
mommy and i are one#\
the government is the enemy#\
Big Brother#\
watch TV#\
buy now#\
destroy#\
main#\
hurt#\
kill#\
free love#\
God is dead.#\
tickle#\
can't trust anyone#\
fish#\
I can fly#\
zymurgy#\
bludgeon#\
salad#\
brassiere#\
turn me on dead man#\
banana#\
P U S !#\
yummy#\
obsession#\
come upstairs#\
kiss me#\
naked men#\
naked women#\
quit smoking#\
don't do drugs#\
violence is the answer#\
maceration#\
formicate#\
bargello#\
mother#\
father#\
beatings#\
alfonzo#\
hamsters#\
seals#\
explosion#\
pink pussycat#\
Rodney#\
don't#\
murder#\
sex#\
arson#\
buiscut barrel#\
screen savers#\
register shareware#\
(C) 1995#\
pleasure#\
dewey#\
edible underwear#\
crotchless#\
pain#\
is good#\
chess#\
you will die someday#\
it happens#\
kumquat#\
attack! attack!#\
toes#\
foot#\
boot#\
god is money#\
money#\
work#\
play#\
speed#\
stop#\
don't stop#\
revolution#\
arnold#\
tulip#\
orchid#\
spaghetti#";

